from enum import Enum


class Features(Enum):
    UNNAMED = 'Unnamed: 0'
    APPLICANT_ETHNICITY = 'applicant_ethnicity'
    INCOME = 'income'
    APPLICANT_RACE_1 = 'applicant_race_1'
    APPLICANT_RACE_2 = 'applicant_race_2'
    APPLICANT_RACE_3 = 'applicant_race_3'
    APPLICANT_RACE_4 = 'applicant_race_4'
    APPLICANT_RACE_5 = 'applicant_race_5'
    APPLICANT_SEX = 'applicant_sex'
    CO_APPLICANT_ETHNICITY = 'co_applicant_ethnicity'
    CO_APPLICANT_RACE_1 = 'co_applicant_race_1'
    CO_APPLICANT_RACE_2 = 'co_applicant_race_2'
    CO_APPLICANT_RACE_3 = 'co_applicant_race_3'
    CO_APPLICANT_RACE_4 = 'co_applicant_race_4'
    CO_APPLICANT_RACE_5 = 'co_applicant_race_5'
    CO_APPLICANT_SEX = 'co_applicant_sex'
    LOAN_PURPOSE = 'loan_purpose'
    LOAN_TYPE = 'loan_type'
    MSAMD = 'msamd'
    PREAPPROVAL = 'preapproval'
    PROPERTY_TYPE = 'property_type'
    PURCHASER_TYPE = 'purchaser_type'
    HUD_MEDIAN_FAMILY_INCOME = 'hud_median_family_income'
    LOAN_AMOUNT = 'loan_amount'
    NUMBER_OF_1_TO_4_FAMILY_UNITS = 'number_of_1_to_4_family_units'
    NUMBER_OF_OWNER_OCCUPIED_UNITS = 'number_of_owner_occupied_units'
    MINORITY_POPULATION = 'minority_population'
    POPULATION = 'population'
    TARGET = 'target'
